// import { Action } from '@ngrx/store';

// import { MonthlyReportReportModel } from 'app/models/reports'

// export const enum MonthlyReportReportActionTypes {
//     FETCH_MONTHLY_REPORTS_REPORT = '[PACKAGE][REPORT] FETCH_MONTHLY_REPORTS_REPORT',
//     FETCH_MONTHLY_REPORTS_REPORT_START = '[PACKAGE][REPORT] FETCH_MONTHLY_REPORTS_REPORT_START',
//     FETCH_MONTHLY_REPORTS_REPORT_SUCCEED = '[PACKAGE][REPORT] FETCH_MONTHLY_REPORTS_REPORT_SUCCEED',
//     FETCH_MONTHLY_REPORTS_REPORT_FAILED = '[PACKAGE][REPORT] FETCH_MONTHLY_REPORTS_REPORT_FAILED',
// }

// export class FetchMonthlyReportReportAction implements Action {
//     readonly type = MonthlyReportReportActionTypes.FETCH_MONTHLY_REPORTS_REPORT;
//     constructor(public payload: MonthlyReportReportModel.Request) { }
// }
// export class FetchMonthlyReportReportStartAction implements Action {
//     readonly type = MonthlyReportReportActionTypes.FETCH_MONTHLY_REPORTS_REPORT_START;
//     constructor(public payload: MonthlyReportReportModel.Request) { }
// }
// export class FetchMonthlyReportReportSucceedAction implements Action {
//     readonly type = MonthlyReportReportActionTypes.FETCH_MONTHLY_REPORTS_REPORT_SUCCEED;
//     constructor(public payload: MonthlyReportReportModel.Response) { }
// }
// export class FetchMonthlyReportReportFailedAction implements Action {
//     readonly type = MonthlyReportReportActionTypes.FETCH_MONTHLY_REPORTS_REPORT_FAILED;
// }

// export type MonthlyReportReportAction =
//     FetchMonthlyReportReportAction
//     | FetchMonthlyReportReportStartAction
//     | FetchMonthlyReportReportSucceedAction
//     | FetchMonthlyReportReportFailedAction;